export const postData = [
    {
      id: 1,
      abbreviation: 'J',
      color: 'red',
      title:"Jone Doe",
      subheader:"January 14, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 2,
      abbreviation: 'R',
      color: 'blue',
      title:"Remy Shark",
      subheader:"February 03, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 3,
      abbreviation: 'S',
      color: 'yellow',
      title:"Seth Nayman",
      subheader:"January 11, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 4,
      abbreviation: 'D',
      color: 'green',
      title:"David Kabul",
      subheader:"March 8, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 5,
      abbreviation: 'A',
      color: 'orange',
      title:"Argwings Norman",
      subheader:"April 4, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 6,
      abbreviation: 'B',
      color: 'purple',
      title:"Beckam Wesley",
      subheader:"February 26, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 7,
      abbreviation: 'W',
      color: 'pink',
      title:"Wendy Elliot",
      subheader:"January 14, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 8,
      abbreviation: 'M',
      color: 'brown',
      title:"May Teresa",
      subheader:"March 10, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
      },
    {
      id: 9,
      abbreviation: 'J',
      color: 'indigo',
      title:"Jacky Thompson",
      subheader:"January 8, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 10,
      abbreviation: 'A',
      color: 'cyan',
      title:"Andrew Cassidy",
      subheader:"January 14, 2024",
      imageUrl: "/static/images/grooving-machine-one.webp",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
      },
  ];
  
  