export const postData = [
    {
      id: 1,
      abbreviation: 'J',
      color: 'red',
      name:"Jone Doe",
      subheader:"January 14, 2024",
      imageUrl: "/post-one.jpg",
      desc: "This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.",
    },
    {
      id: 2,
      abbreviation: 'R',
      color: 'blue',
      name:"Remy Shark",
      subheader:"February 03, 2024",
      imageUrl: "/bonfire.webp",
      desc: "Cozy night under the stars with friends, sharing stories and laughter around a crackling bonfire.  Marshmallows anyone? #friends #bonfirenight #goodvibes",
    },
    {
      id: 3,
      abbreviation: 'S',
      color: 'yellow',
      name:"Seth Nayman",
      subheader:"January 11, 2024",
      imageUrl: "/cathedral.webp",
      desc: "Standing in awe of the architectural marvels of European cathedrals.  Stained glass windows, towering ceilings, and a rich history waiting to be explored. #europetrip #architecturelover #culturalimmersion",
    },
    {
      id: 4,
      abbreviation: 'D',
      color: 'green',
      name:"David Kabul",
      subheader:"March 8, 2024",
      imageUrl: "/dining.webp",
      desc: "Basking in the warm sunshine while enjoying a delicious meal on a charming outdoor patio.  Fresh air and good food, what more could you ask for? #al fresco dining #summervibes #foodie",
    },
    {
      id: 5,
      abbreviation: 'A',
      color: 'orange',
      name:"Argwings Norman",
      subheader:"April 4, 2024",
      imageUrl: "/dogs.webp",
      desc: "There's no truer companion than a furry friend by your side.  Long walks, cuddles on the couch, and endless love - dogs make life better! #doglover #mansbestfriend #pawsitivevibes",
    },
    {
      id: 6,
      abbreviation: 'B',
      color: 'purple',
      name:"Beckam Wesley",
      subheader:"February 26, 2024",
      imageUrl: "/friends.webp",
      desc: "Creating lasting memories with the ones who make you laugh the hardest. Here's to friendships that brighten your day! #squadgoals #friendsforever #goodtimes",
    },
    {
      id: 7,
      abbreviation: 'W',
      color: 'pink',
      name:"Wendy Elliot",
      subheader:"January 14, 2024",
      imageUrl: "/lake.webp",
      desc: "Tranquility found by a still lake, surrounded by lush greenery and the calming sound of nature. Breathe in the fresh air and let your worries melt away. #lakesideliving #findyourpeace #naturelover",
    },
    {
      id: 8,
      abbreviation: 'M',
      color: 'brown',
      name:"May Teresa",
      subheader:"March 10, 2024",
      imageUrl: "/plane.webp",
      desc: "Soaring through the clouds and watching the world shrink beneath you. The magic of flight never gets old! #travelgram #adventureawaits #bucketlist",
      },
    {
      id: 9,
      abbreviation: 'J',
      color: 'indigo',
      name:"Jacky Thompson",
      subheader:"January 8, 2024",
      imageUrl: "/running.webp",
      desc: "Lacing up my shoes and hitting the open road. The wind in my hair, the sun on my face, and the rhythm of my feet - pure freedom in every stride. #runnershigh #outdoors #nofilter",
    },
    {
      id: 10,
      abbreviation: 'A',
      color: 'cyan',
      name:"Andrew Cassidy",
      subheader:"January 14, 2024",
      imageUrl: "/sea.webp",
      desc: "Conquering the waves and feeling the rush of adrenaline as you carve through the crystal-clear ocean. There's nothing quite like the thrill of sea surfing! #surfsup #oceanlife #adventure",
      },
  ];
  
  